version: '3.8'

services:
  backend:
    build: ./backend
    container_name: quizmaster-backend
    restart: always
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION:-604800000}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - SERVER_PORT=8080
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - quizmaster-network
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: quizmaster-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_AUTH_DOMAIN=${NEXT_PUBLIC_AUTH_DOMAIN}
      - NEXT_PUBLIC_ENABLE_AI_FEATURES=${NEXT_PUBLIC_ENABLE_AI_FEATURES:-true}
      - NEXT_PUBLIC_ANALYTICS_ID=${NEXT_PUBLIC_ANALYTICS_ID}
    networks:
      - quizmaster-network
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: quizmaster-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=quizmaster
    volumes:
      - mongodb-data:/data/db
    networks:
      - quizmaster-network

networks:
  quizmaster-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
